name: Vibration Nation
favicon: null
layout_spectrum: 0
typography_spectrum: 0.0542
title: Vibration Nation Charleston
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0b0221'
    - '#ffffff'
    - '#cbb7cc'
    - '#7e6b77'
    - '#b60068'
  brandStrength: 0.5120455876458436
  lightness: 0.21636653575114906
  saturation: 0.010164479725062847
  rhythmicContrast: 0.2867710997816175
purpose: []
